#
Version: 2.0.0
#

#
# This Plugin is created by AloneMusk
# [Be careful with configs!]

#Sends when the player first ever joins the server.
First_Join_Message: "&6Hello %player%, Welcome to server"
Join_Message: "&6Hello %player%, Welcome to server"

First_Join_MOTD:
  - ""
  - ""
  - ""

Join_MOTD:
  - ""
  - ""
  - ""

First_Join_Spawn_Location:
  x: 0
  y: ~
  z: 0
  yaw: 90
  pitch: 0
  world: "world"

Spawn_Location:
  x: 0
  y: ~
  z: 0
  yaw: 90
  pitch: 0
  world: "world"



Quit_Message: "&6%player% left the server"

#
#Options
#

Enable_Void_TP: true
Enable_Force_Teleport: true
Enable_Spawn_Command: true
