#
Version: 2.0.0
#

#
# This Plugin is created by AloneMusk
# [Be careful with configs!]

First_Join_Message: "&6Hello %player_name%, Welcome to server"
Join_Message: "&6Hello %player_name%, Welcome to server"

First_Join_MOTD:
  - ""
  - ""
  - ""

Join_MOTD:
  - ""
  - ""
  - ""

First_Join_Spawn_Location:
  x: 0
  y: ~
  z: 0
  yaw: 90
  pitch: 0
  world: "world"

Spawn_Location:
  x: 0
  y: ~
  z: 0
  yaw: 90
  pitch: 0
  world: "world"

Void_Spawn_Location:
  x: 0
  y: ~
  z: 0
  yaw: 90
  pitch: 0
  world: "world"



Quit_Message: "&6%player_name% left the server"

#
#Options
#

Enable_Void_TP: true
Enable_Force_Teleport: true
Enable_Spawn_Command: true

Options:
  Enable_Spawn_Teleport: true
  Spawn_Teleport_Cooldown: 5
  Enable_Spawn_Countdown_Titles: true


Deaths:
  Gamemode_Before_Respawn: SPECTATOR
  Gamemode_After_Respawn: SURVIVAL
  Enable_Respawn_Countdown_Titles: true
  No_Move_On_Respawn: true
  Skip_Death_Screen: true
  Auto_Fill_Incomplete_Death_Types_With_Default: true
  Types:
    DEFAULT:
      Messages:
        - "%player_name% said \"ALLAHU AKBAR!\""
        - "%player_name% left the lobby on the 9th of September"
        - "%player_name% left the game on the 9th of September"
        - "%player_name% left the chat on the 9th of September"
        - "%player_name% was in Hiroshima on the 6th of August, 1945"
        - "%player_name% joined ISIS"
        - "%player_name% joined Al-Qaeda"
        - "%player_name% started singing \"Here Comes the Sun\""
      Private_Message: "Unfortunately you died and lost $100"
      Money_Penalty: 100
      Level_Penalty: 5
      exp_Penalty: 0
      Titles:
        Title: "You died."
        Subtitle: "You Lost $100"
        FadeIn: 5
        Stay: 5
        FadeOut: 5
      Respawn_Cooldown: 10
      Keep_Inventory: true
      Keep_Levels: true
    FALL:
      Messages:
        - "%player_name% committed seppuku"
        - "%player_name% became a furry"
        - "%player_name% wanted to identify as an attack helicopter"
        - "%player_name%'s Discord kitten left"
      Private_Message: "Unfortunately you died and lost $300"
      Money_Penalty: 300
      Level_Penalty: 5
      exp_Penalty: 0
      Titles:
        Title: "You died from falling"
        Subtitle: "You Lost $300"
        FadeIn: 5
        Stay: 5
        FadeOut: 5
      Respawn_Cooldown: 10
      Keep_Inventory: true
      Keep_Levels: true
    WITHER:
      Messages:
        - "Bill Cosby hit on %player_name%"
        - "%player_name% got molested by Venom"
        - "%player_name% didn't say no to drugs"
        - "%player_name% went trick or treating in Mexico"
    ZOMBIE:
      Messages:
        - "%player_name% was molested by a Zombie"
    PLAYER:
      Messages:
        - "%player_name% died from %killer%"
        - "%player_name% got rabies from %killer%"
        - "&d%killer% mopped the floor with the remains of %player_name%"
        - "&c%killer% used Eggman's super laser piss against %player_name%"
        - "&b%player_name% got raped by %killer%"
      Private_Message: "Unfortunately you died and lost $100"
      Money_Penalty: 100
      Level_Penalty: 5
      exp_Penalty: 0
      Titles:
        Title: "You died."
        Subtitle: "You Lost $100"
        FadeIn: 5
        Stay: 5
        FadeOut: 5
      Respawn_Cooldown: 10
      Keep_Inventory: true
      Keep_Levels: true
      Killer_Money_Reward: 500
      Killer_Exp_Reward: 5000


Titles:
  Join_Title:
    Title: "Welcome back %player_name%"
    Subtitle: "You have %balance%"
    FadeIn: 5
    Stay: 5
    FadeOut: 5
    Delay: 2
  RESPAWN:
    Title: "Respawning in"
    Subtitle: "&b%cooldown% seconds"
    FadeIn: 5
    Stay: 5
    FadeOut: 5
    Delay: 2
  SPAWN_TELEPORTING:
    Title: "Teleporting in"
    Subtitle: "&b%cooldown% seconds"
    FadeIn: 5
    Stay: 5
    FadeOut: 5
    Delay: 2

